# Generated by Django 5.2.3 on 2025-06-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_EstudiantesTecNM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM', models.IntegerField()),
                ('APELLIDOS', models.CharField(max_length=50)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(max_length=50)),
                ('GENERO', models.CharField(max_length=1)),
                ('CONTROL', models.CharField(max_length=10)),
                ('TELEFONO', models.CharField(max_length=10)),
                ('HORARIO', models.CharField(max_length=10)),
                ('INSTITUTO', models.CharField(max_length=100)),
                ('CURP', models.CharField(max_length=20)),
                ('EDAD', models.CharField(max_length=2)),
                ('MODALIDAD', models.CharField(max_length=10)),
                ('SEDE', models.CharField(max_length=10)),
                ('ACTIVIDAD', models.CharField(max_length=30)),
                ('DISCAPACIDAD', models.CharField(max_length=2)),
                ('TIPO', models.CharField(max_length=30)),
                ('APOYO', models.CharField(max_length=5)),
                ('CARRERA', models.CharField(max_length=100)),
                ('AVANCE', models.CharField(max_length=10)),
                ('PROMEDIO', models.CharField(max_length=10)),
                ('EQUIPO', models.CharField(max_length=15)),
                ('PROYECTO_INFOTEC', models.CharField(max_length=100)),
                ('AREA', models.CharField(max_length=100)),
                ('PROYECTO_PROPIO', models.CharField(max_length=100)),
                ('OBJETIVO', models.CharField(max_length=100)),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('TUTOR', models.CharField(max_length=100)),
                ('COTUTOR', models.CharField(max_length=100)),
            ],
        ),
    ]
