# Generated by Django 5.2.3 on 2025-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_table_est_tecnm_delete_table_estudiantestecnm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='ACTIVIDAD',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='APELLIDOS',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='APOYO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='AREA',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='AVANCE',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='CARRERA',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='CONTROL',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='COTUTOR',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='CURP',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='DESCRIPCION',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='DISCAPACIDAD',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='EDAD',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='EMAIL',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='EQUIPO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='GENERO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='HORARIO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='INSTITUTO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='MODALIDAD',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='NOMBRE',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='OBJETIVO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='PROMEDIO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='PROYECTO_INFOTEC',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='PROYECTO_PROPIO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='SEDE',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='TELEFONO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='TIPO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table_est_tecnm',
            name='TUTOR',
            field=models.CharField(blank=True, null=True),
        ),
    ]
